<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="RTZ 2 (зима)">
<General productName="Vugen" productVer="12" os="" host="VOROBYEV_P"><DocLocation><![CDATA[G:\GUC Load\ESVLoad_Serts]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[ESVLoad_Serts]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Summary sTime="14.02.2020 - 9:53:44" eTime="14.02.2020 - 9:53:44" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[VerifyCertificate_simple]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:44]]></Time>
<TimeTick>1581663224</TimeTick>
<NodeArgs eType="General" icon="4" nRep="9" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:44]]></Time>
<TimeTick>1581663224</TimeTick>
<NodeArgs eType="General" icon="5" nRep="10" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:44]]></Time>
<TimeTick>1581663224</TimeTick>
<NodeArgs eType="General" icon="6" nRep="11" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:44]]></Time>
<TimeTick>1581663224</TimeTick>
<NodeArgs eType="General" icon="7" nRep="12" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t33696748.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:44]]></Time>
<TimeTick>1581663224</TimeTick>
<NodeArgs eType="General" icon="7" nRep="13" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t63637942.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[VerifyCertificate_simple]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:45]]></Time>
<TimeTick>1581663225</TimeTick>
<NodeArgs eType="General" icon="8" nRep="14" status="Passed" >
<Disp><![CDATA[VerifyCertificate_simple]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14.02.2020 - 9:53:44" eTime="14.02.2020 - 9:53:45" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[VerifyCertificate_simple Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T11">
<AName><![CDATA[VerifyCertificate_withSignedReport]]></AName>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:45]]></Time>
<TimeTick>1581663225</TimeTick>
<NodeArgs eType="General" icon="4" nRep="17" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:45]]></Time>
<TimeTick>1581663225</TimeTick>
<NodeArgs eType="General" icon="5" nRep="18" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:45]]></Time>
<TimeTick>1581663225</TimeTick>
<NodeArgs eType="General" icon="6" nRep="19" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:45]]></Time>
<TimeTick>1581663225</TimeTick>
<NodeArgs eType="General" icon="7" nRep="20" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t976599.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:45]]></Time>
<TimeTick>1581663225</TimeTick>
<NodeArgs eType="General" icon="7" nRep="21" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1555988.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[VerifyCertificate_withSignedReport]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:46]]></Time>
<TimeTick>1581663226</TimeTick>
<NodeArgs eType="General" icon="8" nRep="22" status="Passed" >
<Disp><![CDATA[VerifyCertificate_withSignedReport]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14.02.2020 - 9:53:45" eTime="14.02.2020 - 9:53:46" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="16" status="Passed" >
<Disp><![CDATA[VerifyCertificate_withSignedReport Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[ESVLoad_Serts Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T18" iterID="2" >
<Action rID="T19">
<AName><![CDATA[VerifyCertificate_simple]]></AName>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:46]]></Time>
<TimeTick>1581663226</TimeTick>
<NodeArgs eType="General" icon="4" nRep="27" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:46]]></Time>
<TimeTick>1581663226</TimeTick>
<NodeArgs eType="General" icon="5" nRep="28" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:47]]></Time>
<TimeTick>1581663227</TimeTick>
<NodeArgs eType="General" icon="6" nRep="29" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:47]]></Time>
<TimeTick>1581663227</TimeTick>
<NodeArgs eType="General" icon="7" nRep="30" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t2319519.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:47]]></Time>
<TimeTick>1581663227</TimeTick>
<NodeArgs eType="General" icon="7" nRep="31" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t46524950.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[VerifyCertificate_simple]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:47]]></Time>
<TimeTick>1581663227</TimeTick>
<NodeArgs eType="General" icon="8" nRep="32" status="Passed" >
<Disp><![CDATA[VerifyCertificate_simple]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14.02.2020 - 9:53:46" eTime="14.02.2020 - 9:53:47" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="26" status="Passed" >
<Disp><![CDATA[VerifyCertificate_simple Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T26">
<AName><![CDATA[VerifyCertificate_withSignedReport]]></AName>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:48]]></Time>
<TimeTick>1581663228</TimeTick>
<NodeArgs eType="General" icon="4" nRep="35" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:48]]></Time>
<TimeTick>1581663228</TimeTick>
<NodeArgs eType="General" icon="5" nRep="36" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:48]]></Time>
<TimeTick>1581663228</TimeTick>
<NodeArgs eType="General" icon="6" nRep="37" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:48]]></Time>
<TimeTick>1581663228</TimeTick>
<NodeArgs eType="General" icon="7" nRep="38" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t80413368.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:48]]></Time>
<TimeTick>1581663228</TimeTick>
<NodeArgs eType="General" icon="7" nRep="39" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t13618515.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[VerifyCertificate_withSignedReport]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:48]]></Time>
<TimeTick>1581663228</TimeTick>
<NodeArgs eType="General" icon="8" nRep="40" status="Passed" >
<Disp><![CDATA[VerifyCertificate_withSignedReport]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14.02.2020 - 9:53:47" eTime="14.02.2020 - 9:53:49" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="34" status="Passed" >
<Disp><![CDATA[VerifyCertificate_withSignedReport Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="25" status="Passed" >
<Disp><![CDATA[ESVLoad_Serts Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T33" iterID="3" >
<Action rID="T34">
<AName><![CDATA[VerifyCertificate_simple]]></AName>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:49]]></Time>
<TimeTick>1581663229</TimeTick>
<NodeArgs eType="General" icon="4" nRep="45" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:49]]></Time>
<TimeTick>1581663229</TimeTick>
<NodeArgs eType="General" icon="5" nRep="46" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:49]]></Time>
<TimeTick>1581663229</TimeTick>
<NodeArgs eType="General" icon="6" nRep="47" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:49]]></Time>
<TimeTick>1581663229</TimeTick>
<NodeArgs eType="General" icon="7" nRep="48" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration3\t2471008.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:49]]></Time>
<TimeTick>1581663229</TimeTick>
<NodeArgs eType="General" icon="7" nRep="49" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration3\t29516235.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[VerifyCertificate_simple]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:50]]></Time>
<TimeTick>1581663230</TimeTick>
<NodeArgs eType="General" icon="8" nRep="50" status="Passed" >
<Disp><![CDATA[VerifyCertificate_simple]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14.02.2020 - 9:53:49" eTime="14.02.2020 - 9:53:50" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="44" status="Passed" >
<Disp><![CDATA[VerifyCertificate_simple Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T41">
<AName><![CDATA[VerifyCertificate_withSignedReport]]></AName>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:50]]></Time>
<TimeTick>1581663230</TimeTick>
<NodeArgs eType="General" icon="4" nRep="53" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:50]]></Time>
<TimeTick>1581663230</TimeTick>
<NodeArgs eType="General" icon="5" nRep="54" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:50]]></Time>
<TimeTick>1581663230</TimeTick>
<NodeArgs eType="General" icon="6" nRep="55" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:50]]></Time>
<TimeTick>1581663230</TimeTick>
<NodeArgs eType="General" icon="7" nRep="56" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration3\t96103432.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:51]]></Time>
<TimeTick>1581663231</TimeTick>
<NodeArgs eType="General" icon="7" nRep="57" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration3\t5233855.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[VerifyCertificate_withSignedReport]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:51]]></Time>
<TimeTick>1581663231</TimeTick>
<NodeArgs eType="General" icon="8" nRep="58" status="Passed" >
<Disp><![CDATA[VerifyCertificate_withSignedReport]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14.02.2020 - 9:53:50" eTime="14.02.2020 - 9:53:51" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="52" status="Passed" >
<Disp><![CDATA[VerifyCertificate_withSignedReport Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="43" status="Passed" >
<Disp><![CDATA[ESVLoad_Serts Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T48" iterID="4" >
<Action rID="T49">
<AName><![CDATA[VerifyCertificate_simple]]></AName>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:51]]></Time>
<TimeTick>1581663231</TimeTick>
<NodeArgs eType="General" icon="4" nRep="63" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:52]]></Time>
<TimeTick>1581663232</TimeTick>
<NodeArgs eType="General" icon="5" nRep="64" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:52]]></Time>
<TimeTick>1581663232</TimeTick>
<NodeArgs eType="General" icon="6" nRep="65" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:52]]></Time>
<TimeTick>1581663232</TimeTick>
<NodeArgs eType="General" icon="7" nRep="66" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t62364676.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:52]]></Time>
<TimeTick>1581663232</TimeTick>
<NodeArgs eType="General" icon="7" nRep="67" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t74377874.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[VerifyCertificate_simple]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:52]]></Time>
<TimeTick>1581663232</TimeTick>
<NodeArgs eType="General" icon="8" nRep="68" status="Passed" >
<Disp><![CDATA[VerifyCertificate_simple]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14.02.2020 - 9:53:51" eTime="14.02.2020 - 9:53:53" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="62" status="Passed" >
<Disp><![CDATA[VerifyCertificate_simple Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T56">
<AName><![CDATA[VerifyCertificate_withSignedReport]]></AName>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:53]]></Time>
<TimeTick>1581663233</TimeTick>
<NodeArgs eType="General" icon="4" nRep="71" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:53]]></Time>
<TimeTick>1581663233</TimeTick>
<NodeArgs eType="General" icon="5" nRep="72" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:53]]></Time>
<TimeTick>1581663233</TimeTick>
<NodeArgs eType="General" icon="6" nRep="73" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:53]]></Time>
<TimeTick>1581663233</TimeTick>
<NodeArgs eType="General" icon="7" nRep="74" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t40728965.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:53]]></Time>
<TimeTick>1581663233</TimeTick>
<NodeArgs eType="General" icon="7" nRep="75" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t87691928.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[VerifyCertificate_withSignedReport]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[14.02.2020 - 9:53:54]]></Time>
<TimeTick>1581663234</TimeTick>
<NodeArgs eType="General" icon="8" nRep="76" status="Passed" >
<Disp><![CDATA[VerifyCertificate_withSignedReport]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14.02.2020 - 9:53:53" eTime="14.02.2020 - 9:53:54" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="70" status="Passed" >
<Disp><![CDATA[VerifyCertificate_withSignedReport Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="61" status="Passed" >
<Disp><![CDATA[ESVLoad_Serts Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>