<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="RTZ 2 (зима)">
<General productName="Vugen" productVer="12" os="" host="VOROBYEV_P"><DocLocation><![CDATA[G:\GUC Load\ESVLoad]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[ESVLoad]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Summary sTime="12.02.2020 - 18:47:09" eTime="12.02.2020 - 18:47:09" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[VerifyCMSSignature_withSignedReport]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:09]]></Time>
<TimeTick>1581522429</TimeTick>
<NodeArgs eType="General" icon="4" nRep="9" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:09]]></Time>
<TimeTick>1581522429</TimeTick>
<NodeArgs eType="General" icon="5" nRep="10" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:09]]></Time>
<TimeTick>1581522429</TimeTick>
<NodeArgs eType="General" icon="6" nRep="11" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:09]]></Time>
<TimeTick>1581522429</TimeTick>
<NodeArgs eType="General" icon="7" nRep="12" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t23449415.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:09]]></Time>
<TimeTick>1581522429</TimeTick>
<NodeArgs eType="General" icon="7" nRep="13" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t37188276.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[VerifyCMSSignature_withSignedReport]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:11]]></Time>
<TimeTick>1581522431</TimeTick>
<NodeArgs eType="General" icon="8" nRep="14" status="Passed" >
<Disp><![CDATA[VerifyCMSSignature_withSignedReport]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12.02.2020 - 18:47:09" eTime="12.02.2020 - 18:47:11" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[VerifyCMSSignature_withSignedReport Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T11">
<AName><![CDATA[VerifyCMSSignatureByHash_simple]]></AName>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:11]]></Time>
<TimeTick>1581522431</TimeTick>
<NodeArgs eType="General" icon="4" nRep="17" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:11]]></Time>
<TimeTick>1581522431</TimeTick>
<NodeArgs eType="General" icon="5" nRep="18" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:11]]></Time>
<TimeTick>1581522431</TimeTick>
<NodeArgs eType="General" icon="6" nRep="19" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:11]]></Time>
<TimeTick>1581522431</TimeTick>
<NodeArgs eType="General" icon="7" nRep="20" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t54631130.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:12]]></Time>
<TimeTick>1581522432</TimeTick>
<NodeArgs eType="General" icon="7" nRep="21" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t3247752.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[VerifyCMSSignatureByHash_simple]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:12]]></Time>
<TimeTick>1581522432</TimeTick>
<NodeArgs eType="General" icon="8" nRep="22" status="Passed" >
<Disp><![CDATA[VerifyCMSSignatureByHash_simple]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12.02.2020 - 18:47:11" eTime="12.02.2020 - 18:47:12" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="16" status="Passed" >
<Disp><![CDATA[VerifyCMSSignatureByHash_simple Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T18">
<AName><![CDATA[VerifyCMSSignature_simple]]></AName>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:12]]></Time>
<TimeTick>1581522432</TimeTick>
<NodeArgs eType="General" icon="4" nRep="25" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:12]]></Time>
<TimeTick>1581522432</TimeTick>
<NodeArgs eType="General" icon="5" nRep="26" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:12]]></Time>
<TimeTick>1581522432</TimeTick>
<NodeArgs eType="General" icon="6" nRep="27" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:13]]></Time>
<TimeTick>1581522433</TimeTick>
<NodeArgs eType="General" icon="7" nRep="28" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t94054460.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:13]]></Time>
<TimeTick>1581522433</TimeTick>
<NodeArgs eType="General" icon="7" nRep="29" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t14216555.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[VerifyCMSSignature_simple]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:13]]></Time>
<TimeTick>1581522433</TimeTick>
<NodeArgs eType="General" icon="8" nRep="30" status="Passed" >
<Disp><![CDATA[VerifyCMSSignature_simple]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12.02.2020 - 18:47:12" eTime="12.02.2020 - 18:47:13" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="24" status="Passed" >
<Disp><![CDATA[VerifyCMSSignature_simple Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T25">
<AName><![CDATA[VerifyCMSSignatureDetached_simple]]></AName>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:14]]></Time>
<TimeTick>1581522434</TimeTick>
<NodeArgs eType="General" icon="4" nRep="33" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:14]]></Time>
<TimeTick>1581522434</TimeTick>
<NodeArgs eType="General" icon="5" nRep="34" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:14]]></Time>
<TimeTick>1581522434</TimeTick>
<NodeArgs eType="General" icon="6" nRep="35" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:14]]></Time>
<TimeTick>1581522434</TimeTick>
<NodeArgs eType="General" icon="7" nRep="36" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t10394350.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:14]]></Time>
<TimeTick>1581522434</TimeTick>
<NodeArgs eType="General" icon="7" nRep="37" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t29569712.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[VerifyCMSSignatureDetached_simple]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:14]]></Time>
<TimeTick>1581522434</TimeTick>
<NodeArgs eType="General" icon="8" nRep="38" status="Passed" >
<Disp><![CDATA[VerifyCMSSignatureDetached_simple]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12.02.2020 - 18:47:13" eTime="12.02.2020 - 18:47:15" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="32" status="Passed" >
<Disp><![CDATA[VerifyCMSSignatureDetached_simple Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T32">
<AName><![CDATA[VerifyCMSSignatureByHash_withSignedReport]]></AName>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:15]]></Time>
<TimeTick>1581522435</TimeTick>
<NodeArgs eType="General" icon="4" nRep="41" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:15]]></Time>
<TimeTick>1581522435</TimeTick>
<NodeArgs eType="General" icon="5" nRep="42" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:15]]></Time>
<TimeTick>1581522435</TimeTick>
<NodeArgs eType="General" icon="6" nRep="43" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:15]]></Time>
<TimeTick>1581522435</TimeTick>
<NodeArgs eType="General" icon="7" nRep="44" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t47788652.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:15]]></Time>
<TimeTick>1581522435</TimeTick>
<NodeArgs eType="General" icon="7" nRep="45" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t26816969.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[VerifyCMSSignatureByHash_withSignedReport]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:16]]></Time>
<TimeTick>1581522436</TimeTick>
<NodeArgs eType="General" icon="8" nRep="46" status="Passed" >
<Disp><![CDATA[VerifyCMSSignatureByHash_withSignedReport]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12.02.2020 - 18:47:15" eTime="12.02.2020 - 18:47:16" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="40" status="Passed" >
<Disp><![CDATA[VerifyCMSSignatureByHash_withSignedReport Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T39">
<AName><![CDATA[VerifyCMSSignatureDetached_withSignedReport]]></AName>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:16]]></Time>
<TimeTick>1581522436</TimeTick>
<NodeArgs eType="General" icon="4" nRep="49" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:16]]></Time>
<TimeTick>1581522436</TimeTick>
<NodeArgs eType="General" icon="5" nRep="50" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:16]]></Time>
<TimeTick>1581522436</TimeTick>
<NodeArgs eType="General" icon="6" nRep="51" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:17]]></Time>
<TimeTick>1581522437</TimeTick>
<NodeArgs eType="General" icon="7" nRep="52" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t12046607.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:17]]></Time>
<TimeTick>1581522437</TimeTick>
<NodeArgs eType="General" icon="7" nRep="53" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t54781165.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[VerifyCMSSignatureDetached_withSignedReport]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:17]]></Time>
<TimeTick>1581522437</TimeTick>
<NodeArgs eType="General" icon="8" nRep="54" status="Passed" >
<Disp><![CDATA[VerifyCMSSignatureDetached_withSignedReport]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12.02.2020 - 18:47:16" eTime="12.02.2020 - 18:47:18" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="48" status="Passed" >
<Disp><![CDATA[VerifyCMSSignatureDetached_withSignedReport Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T46">
<AName><![CDATA[VerifyPAdES_simple]]></AName>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:18]]></Time>
<TimeTick>1581522438</TimeTick>
<NodeArgs eType="General" icon="4" nRep="57" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:18]]></Time>
<TimeTick>1581522438</TimeTick>
<NodeArgs eType="General" icon="5" nRep="58" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:18]]></Time>
<TimeTick>1581522438</TimeTick>
<NodeArgs eType="General" icon="6" nRep="59" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:18]]></Time>
<TimeTick>1581522438</TimeTick>
<NodeArgs eType="General" icon="7" nRep="60" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t86617908.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:18]]></Time>
<TimeTick>1581522438</TimeTick>
<NodeArgs eType="General" icon="7" nRep="61" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t2073385.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[VerifyPAdES_simple]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:19]]></Time>
<TimeTick>1581522439</TimeTick>
<NodeArgs eType="General" icon="8" nRep="62" status="Passed" >
<Disp><![CDATA[VerifyPAdES_simple]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12.02.2020 - 18:47:18" eTime="12.02.2020 - 18:47:19" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="56" status="Passed" >
<Disp><![CDATA[VerifyPAdES_simple Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T53">
<AName><![CDATA[VerifyPAdES_withSignedReport]]></AName>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:19]]></Time>
<TimeTick>1581522439</TimeTick>
<NodeArgs eType="General" icon="4" nRep="65" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Stop adding customized headers to subsequent HTTP requests</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:19]]></Time>
<TimeTick>1581522439</TimeTick>
<NodeArgs eType="General" icon="5" nRep="66" >
<Disp><![CDATA[Service: Cleanup Auto Headers]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Cookies]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Remove all the cookies that are currently stored by the Vuser</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:19]]></Time>
<TimeTick>1581522439</TimeTick>
<NodeArgs eType="General" icon="6" nRep="67" >
<Disp><![CDATA[Service: Cleanup Cookies]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:19]]></Time>
<TimeTick>1581522439</TimeTick>
<NodeArgs eType="General" icon="7" nRep="68" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t451944.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:20]]></Time>
<TimeTick>1581522440</TimeTick>
<NodeArgs eType="General" icon="7" nRep="69" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t13581026.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[VerifyPAdES_withSignedReporte]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>SOAP request was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:20]]></Time>
<TimeTick>1581522440</TimeTick>
<NodeArgs eType="General" icon="8" nRep="70" status="Passed" >
<Disp><![CDATA[VerifyPAdES_withSignedReporte]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12.02.2020 - 18:47:19" eTime="12.02.2020 - 18:47:21" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="64" status="Passed" >
<Disp><![CDATA[VerifyPAdES_withSignedReport Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T60">
<AName><![CDATA[VerifyCADES_simple]]></AName>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Service: Cache Cleanup]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Clear the contents of the cache simulator</CENTER>]]></Details>
<Time><![CDATA[12.02.2020 - 18:47:21]]></Time>
<TimeTick>1581522441</TimeTick>
<NodeArgs eType="General" icon="4" nRep="73" >
<Disp><![CDATA[Service: Cache Cleanup]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Service: Cleanup Auto Headers]]></Obj>